name: tourism_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  #  package
  flutter_svg: ^2.0.7
  otp_pin_field: ^1.2.2
  flutter_screenutil: ^5.8.4
  syncfusion_flutter_sliders: ^22.2.11
  conditional_builder_null_safety: ^0.0.6
  full_screen_image_null_safe: ^2.0.0
  flutter_timer_countdown: ^1.0.5
  curved_navigation_bar: ^1.0.3
  table_calendar: ^3.0.9
  icon_broken: ^1.1.0
  video_player: ^2.7.1
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.1
  fluttertoast: ^8.2.2



  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  intl: any

  # firebase
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  firebase_storage: any
  google_sign_in: any


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/Card.png


  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Bold.ttf
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 700
